levels = [
    [
        "PPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                       P",
        "P PPPPPPPPPPPPPPPPPPP   P",
        "P                       P",
        "P   PPPPPPPPPPPPPPPPPPPPP",
        "P                       P",
        "P PPPPPPPPPPPPPPPPPPP   P",
        "P                       P",
        "P   PPPPPPPPPPPPPPPPPPPPP",
        "P                       P",
        "P PPPPPPPPPPPPPPPPPPP   P",
        "P                       P",
        "P   PPPPPPPPPPPPPPPPPPPPP",
        "P                       P",
        "P PPPPPPPPPPPPPPPPPPP   P",
        "P                       P",
        "P   PPPPPPPPPPPPPPPPPPPPP",
		"P                      EP",
        "PPPPPPPPPPPPPPPPPPPPPPPPP",
    ],
    [
        "PPPPPPPPPPPPPPPPPPPPPPPPP",
        "P  P                    P",
        "P  PPPPPP               P",
        "P  P     P    P         P",
        "P  P      P   P         P",
        "P  P       P  P         P",
        "P  P         PP    PPPPPP",
        "P  P        P P         P",
        "P  P       P  P         P",
        "P  P      P   PPPPPP    P",
        "P  P     P    PP        P",
        "P  P PP       PPP      PP",
        "P  PPPPP      PPPP    PPP",
        "P       P     PPPPP  PPPP",
        "P        PP   P         P",
        "P            PP         P",
        "P          PP P         P",
        "P       PP    P         P",
        "P      PPPP   PE        P",
        "PPPPPPPPPPPPPPPPPPPPPPPPP",
    ],
    [
        "PPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                       P",
        "P                       P",
        "PP  P  P   P   P   P  PPP",
        "PPP    P   P   P   P  PPP",
        "PPPP   P   P   P   P  PPP",
        "PPPPP      P   P   P  PPP",
        "PPPPPP     P   P   P  PPP",
        "PPPPPPP    P   P   P  PPP",
        "PPPPPPPP   P   P   P  PPP",
        "PPPPPPPPP      P   P  PPP",
        "PPPPPPPPPP     P   P  PPP",
        "PPPPPPPPPPP    P   P  PPP",
        "PPPPPPPPPPPP   P   P  PPP",
        "PPPPPPPPPPPPP      P  PPP",
        "PPPPPPPPPPPPPP     P  PPP",
        "PPPPPPPPPPPPPPP    P  PPP",
        "PPPPPPPPPPPPPPPPPPPP  PPP",
        "PE                    PPP",
        "PPPPPPPPPPPPPPPPPPPPPPPPP",
    ]
]